name: Build with lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Run detekt
      run: ./gradlew detekt

    - name: Build plugin
      run: ./gradlew buildPlugin
